version: "3.9"

services:
  backend:
    build: ./backend
    container_name: myapp_backend
    ports:
      - "8080:8080"
    networks:
      - myapp_network

  nginx:
    build: ./nginx
    container_name: myapp_nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - myapp_network

networks:
  myapp_network:
    driver: bridge
